### ISSUE TITLE
php-docker FPM vs CLI images consistency

### ISSUE THREAD

**Issue by kyriog** [jtreminio/php-docker#10]
Currently, you're providing in this repository two type of docker images: one with PHP FPM+CLI, which are the main images deployed on the Docker Hub, but you also provide Dockerfiles for PHP-CLI which don't seem to be available on the hub.

Are these images still up to date?

Currently, this create a consistency problem, because they're not based on the same images, which may lead to some weird behaviors if this particularity hasn't been handled correctly by the developer.

In my #9 use case, I need to get a fully configured PHP environment to run crons (which also mean based on phusion-baseimage or similar), but I do not need FPM on this environment.
I currently run two separate containers because I want to be able to run multiple FPM for scaling my frontend, whereas I only need one cron container to be run.
I currently remove the /etc/service/fpm directory in my cron container, but I find this is a pretty bad behavior considering Docker's philosophy.

Would you consider to deliver two images, one with only PHP-CLI only, and one with PHP-FPM which will be based on the PHP-CLI one? This would make the images very lightweight to manage in my case.

The only problem I see is the way to manage FPM specific ENV variables, but I guess it could be okay to keep them in the baseimage for CLI image.

What do you think about this idea and/or do you have any better approach to my use case?

**Comment by jtreminio** [comment]
Sorry for lack of response on this - new job has kept me crazy busy.

Thank you for the idea, I implemented it in a slightly different way, but it now goes

                       | apache
    env -> cli -> fpm -|
                       | nginx
