### ISSUE TITLE
Alpine based images?

### ISSUE THREAD

**Issue by pwFoo** [jtreminio/php-docker#13]
Hi,
I built an alpine based image (php 7.3) and it's just 45,5MB (compressed 17,52MB) on size.

First I tried to prepare the original php.ini with sed / awk to replace values with variables, but after code execution the result wasn't rendered. Instead it was offered as file download.
I replaced my php.ini with yours and added the ENV vars and it fixed my problem.

Any plans to move from ubuntu base to alpine? I like the small and nice base for docker images.

**Comment by jtreminio** [comment]
I chose Ubuntu specifically because it allows the use of Ondrej's PPA: https://launchpad.net/~ondrej/+archive/ubuntu/php

This is a huge leg-up on building on Alpine and having to manage extension module files manually.
