### ISSUE TITLE
new xdebug missing env vars

### ISSUE THREAD

**Issue by clenn** [jtreminio/php-docker#18]
Hi,

apparently there's been a update on extisting images?  
jtreminio/php:7.4  now uses version xdebug 3.0.1

because  xdebug 3.0.1 uses a couple of new settings, it would be nice to add them to your php.ini and add them as ENVs to your dockerfile:

i.e:

xdebug.client_host = ${PHP.xdebug.client_host}
xdebug.client_port = ${PHP.xdebug.client_port}
xdebug.mode=${PHP.xdebug.mode}

thanks in advance :D

**Comment by jtreminio** [comment]
I actually just ran into this problem this morning. I'll push updates in a few minutes.

**Comment by jtreminio** [comment]
Fixed by https://github.com/jtreminio/php-docker/commit/1fa7714a99ccc462db107408cccf9616bd4f7bc6
