### ISSUE TITLE
unable to parse env file

### ISSUE THREAD

**Issue by valentinomariotto** [jtreminio/php-docker#25]
Hi! thank you for this great job. Using this image brings me some troubles with Laravel and Composer. In particular it seems that php is unable to parse the .env file correctly, but only when called by certain functions.
See these errors: https://laravel.io/forum/problem-parsing-env-filela
https://laravel.io/forum/schedulerun-calls-for-translation-and-causes-an-exception

```
PHP Warning:  Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
The environment file is invalid!
Failed to parse dotenv file. Encountered an invalid name at [APP_NAME].
```

I tried the same code on the laravel sail host (based on ubuntu 18, with apache), and it works. I tried to add the missing php extensions without luck. What do you reckon might be the cause? some nginx setting?
Thank you

**Comment by jtreminio** [comment]
Can you show me examples of command you are trying to run? Is the error happening when building container?

**Comment by valentinomariotto** [comment]
Hi Juan, thank you for replying. 

Are you familiar with Laravel? It has a special script called "artisan" which is used to call all other scripts and operations.

I have a few php scripts that are supposed to be executed in the CLI, and are called with cli commands such as this:
`php artisan import:users `

The scripts run without issue. The website also runs fine and regularly uses parameters from the .env file.

BUT when I use the laravel kernel scheduler to call those same scripts, I get that error.
The scheduler is nothing special per se. You set a cron job in your server to run 
`php artisan schedule:run`
every minute, and laravel calls the appropriate scripts to execute depending on the schedule.

Of course I thought it was an issue with Laravel and tried to get help on their forum and on StackOverflow:
https://laravel.io/forum/problem-parsing-env-filela
https://stackoverflow.com/questions/73766929/composer-php-unknown-error-after-update

But I didn't get much help. In the meantime, by trying out another server, I found that the issue disappeared.
So there must be something not quite right between Laravel, Nginx and PHP.

**Comment by valentinomariotto** [comment]
I'm giving this another try, and I figure that it all probably come down to this:

I can run /var/www/artisan both as root and as admin. 

```
root# php artisan cache:clear 
root# su www
www$ php artisan cache:clear 
```

but using the su command with the -c option, fails as follows:
```
root# su -c "php /var/www/artisan cache:clear" - www
PHP Warning:  Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
```

Then I noticed your notes

> # NOTE:
> # - do not start in interactive mode -it or the init scripts won't run
> # - there's setuser as an alternative to su and sudo

This is not mentioned in the wiki. 
Anyways, doing this works:

`root# setuser www php /var/www/artisan cache:clear`


the task scheduler issue seems to have resolved itself as well, somehow... 
So I'm closing this issue but I think it'd be nice if you mentioned (and explained) those limitations with su and sudo in the readme.md
Thank you very much!
