### ISSUE TITLE
Dot env vars exporting

### ISSUE THREAD

**Issue by kyriog** [jtreminio/php-docker#9]
You're using "dot env var" names for defining PHP ini settings during runtime.
This is pretty handy for setting PHP configuration with Docker, but has a huge caveat under certain conditions.

In my case, I need to make a PHP script to run using a cron job.
Pretty handy, phusion-baseimage automatically starts the cron daemon, so I just have to add the PHP script in the crontab to make it run.

First problem is that the docker env vars will not be declared, which makes the PHP CLI pretty buggy (because all PHP ini settings will use `""` or `0`).
This is not a big deal for now, because phusion-baseimage gives us the handy `/etc/container_environment.sh` script which automatically sets all docker env vars.

The problem is that `export` cannot handle dots in var names:
```
root@e1ef3bb549ff:~# export PHP.zend.enable_gc=1
bash: export: `PHP.zend.enable_gc=1': not a valid identifier
```

phusion-baseimage currently prevents such errors by sanitizing var names, which replaces all dots by underscores:
```
root@e1ef3bb549ff:~# cat /etc/container_environment.sh | grep zend_enable_gc
export PHP_zend_enable_gc=1
```

Could it be a solution to replace all dots by underscores in the php.ini (and therefore in Dockerfile-env)? Or maybe double underscores to keep the "separator" (`PHP__zend__enable_gc`)?

**Comment by jtreminio** [comment]
From a technical standpoint, it should not matter to me that we replace `PHP.` with `PHP_`.

However, I modeled the env vars after elasticsearch (and several others) that use this naming scheme:

    docker run \
        -p 9200:9200
        -p 9300:9300
        -e "discovery.type=single-node"
        docker.elastic.co/elasticsearch/elasticsearch:6.4.3

I _know_ dots don't work in names in bash, but I do think it highlights the fact that you shouldn't be setting the INI values within the docker container in the first place. The container itself should be receiving these INI values, doing its work, then exiting.

You can also pass INI values in the CLI directly:

    root@0c2125cbd70a:/etc/php/7.4# php -i | grep report_zend_debug
    report_zend_debug => Off => Off
    PHP.report_zend_debug => 0

    root@0c2125cbd70a:/etc/php/7.4# php -d report_zend_debug=1 -i | grep report_zend_debug
    report_zend_debug => On => On
    PHP.report_zend_debug => 0

And finally, you can also write to the custom INI files:

    root@0c2125cbd70a:/etc/php/7.4# php --ini
    Configuration File (php.ini) Path: /etc/php/7.4/cli
    Loaded Configuration File:         /etc/php/7.4/cli/php.ini
    Scan for additional .ini files in: /etc/php/7.4/cli/conf.d
    Additional .ini files parsed:      
    [...]
    /etc/php/7.4/cli/conf.d/99-custom.ini

    root@0c2125cbd70a:/etc/php/7.4# cat /etc/php/7.4/cli/conf.d/99-custom.ini
    ; Add custom PHP INI directives here

    root@0c2125cbd70a:/etc/php/7.4# printf 'report_zend_debug=1\n' >> /etc/php/7.4/cli/conf.d/99-custom.ini

    root@0c2125cbd70a:/etc/php/7.4# php -d report_zend_debug=1 -i | grep report_zend_debug
    report_zend_debug => On => On
    PHP.report_zend_debug => 0

Hope these are enough.
